django/integration_project/apps/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r"^$", views.index, name="index"),
	url(r"^create$", views.create, name="create"),
	url(r"^destroy/(?P<id>\d+)$", views.destroy, name="destroy"),
	url(r"^delete$", views.delete, name="delete"),
	url(r"^roster$", views.roster, name="roster"),
	url(r"^add_user$", views.add_user, name="add_user"),
]

django/integration_project/apps/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r"^$", views.index, name="index"),
]

django/integration_project/integration_project/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^', include('apps.urls', namespace='top')),
    url(r'^courses/', include('apps.courses.urls', namespace='courses')),
    url(r'^disappear/', include('apps.disappear.urls', namespace='disappear')),
    url(r'^loginReg/', include('apps.loginReg.urls', namespace='loginReg')),
    url(r'^randomWord/', include('apps.randomWord.urls', namespace='randomWord')),
    url(r'^surveyApp/', include('apps.surveyApp.urls', namespace='surveyApp')),
]

django/integration_project/apps/courses/models.py
from __future__ import unicode_literals

from django.db import models
from ..loginReg.models import User

# Create your models here.
class Course(models.Model):
	name = models.CharField(max_length=50)
	description = models.CharField(max_length=255)
	users = models.ManyToManyField(User, related_name = "courses")
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

django/integration_project/apps/courses/views.py
from django.shortcuts import render, redirect
from .models import Course
from ..loginReg.models import User

# Create your views here.
def index(request):
    context = {
        "the_courses": Course.objects.all()
    }
    return render(request, "courses/index.html", context)

def create(request):    # process course creation form
    if request.method == "POST":
        Course.objects.create(name=request.POST['name'], description=request.POST['description'])
    return redirect("courses:index")

def destroy(request, id):   # prompt for course deletion
    course = Course.objects.get(id=id)
    context = {
        "course": course
    }
    return render(request, "courses/destroy.html", context)

def delete(request):    # process course deletion form
    if request.method == "POST":
        print "ID= ", request.POST['id']
        if request.POST['response'] == "Yes":
            course = Course.objects.get(id=request.POST['id'])
            course.delete()
    return redirect("courses:index")

def roster(request):
    context = {
        "the_users": User.objects.all(),
        "the_courses": Course.objects.all()
    }
    return render(request, "courses/users_courses.html", context)

def add_user(request):    # process course creation form
    if request.method == "POST":
        user_id = request.POST['user_id']
        course_id = request.POST['course_id']
        print user_id, course_id
        if (user_id != "0" and course_id != "0"):  # validity check
            this_user = User.objects.get(id=user_id)
            this_course = Course.objects.get(id=course_id)
            this_course.users.add(this_user)
    return redirect("courses:roster")

django/integration_project/apps/courses/templates/courses/destroy.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Delete a Course</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'courses/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <!-- <h3>Delete a Course</h3> -->
    <h3>Are you sure you want to delete the following course?</h3>
    <p>Name: {{course.name}}</p>
    <p>Description: {{course.description}}</p>
		<form action="{% url 'courses:delete' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="id" value="{{course.id}}">
      <button class="gray" type="submit" name="response" value="No">No</button>
      <button class="red" type="submit" name="response" value="Yes">Yes! I want to delete this</button>
    </form>
  </body>
</html>

django/integration_project/apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bootcamp Course List</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'courses/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <!-- <h3>Bootcamp Course List</h3> -->
    <h3>Add a New Course</h3>
		<form action="{% url 'courses:create' %}" method="post">
      {% csrf_token %}
			Name: <input type="text" name="name">
			<p></p>
			Description: <textarea name="description" rows="4" cols="60"></textarea>
			<p></p>
      <input class="green" type="submit" value="Add">
    </form>
		<h3>Courses</h3>
		<table>
			<thead>
				<tr>
					<th>Course Name</th>
					<th>Description</th>
					<th>Date Added</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for course in the_courses %}
				<!-- <p>{{course.name}} {{course.id}}</p> -->
					<tr>
						<td>{{course.name}}</td>
						<td>{{course.description}}</td>
						<td>{{course.created_at}}</td>
            <td><a href="destroy/{{course.id}}" alt="remove">remove</a></td>
						<!-- <td><a href=" url 'courses:destroy' /{{course.id}}" alt="remove">remove</a></td> -->
					</tr>
				{% endfor %}
			</tbody>
		</table>
    <p></p>
    <form action="{% url 'courses:roster' %}" method="post">
      {% csrf_token %}
      <input type="submit" name="return" value="View Course Roster">
    </form>
  </body>
</html>

django/integration_project/apps/courses/templates/courses/users_courses.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bootcamp Course User Roster</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'courses/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <h3>Bootcamp Course Roster</h3>
		<form action="{% url 'courses:add_user' %}" method="post">
      {% csrf_token %}
      <select name="user_id">
        <option value="0" selected>Users</option>
        {% for user in the_users %}
        <option value="{{user.id}}">{{user.last_name}}</option>
        {% endfor %}
      </select>
      <select name="course_id">
        <option value="0" selected>Courses</option>
        {% for course in the_courses %}
        <option value="{{course.id}}">{{course.name}}</option>
        {% endfor %}
      </select>
			<p></p>
      <input type="submit" value="Add User to Course">
    </form>
    <p></p>
    <table>
      <thead>
        <tr>
          <th>Course</th>
          <th>Title</th>
          <th>Number of Users</th>
          <th>List of Users Enrolled</th>
        </tr>
      </thead>
      <tbody>
        {% for course in the_courses %}
          <tr>
            <td>{{course.id}}</td>
            <td>{{course.name}}</td>
            <td>{{course.users.count}}</td>
            <td>{% for user in course.users.all %} {{user.last_name}} {% endfor %}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <p></p>
    <form action="{% url 'courses:index' %}" method="post">
      {% csrf_token %}
      <input class="green" type="submit" name="return" value="Return Home">
    </form>
  </body>
</html>