django/integration_project/apps/loginReg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r"^$", views.index, name="index"),
	url(r"^register$", views.register, name="register"),
	url(r"^login$", views.login, name="login"),
	url(r"^logout$", views.logout, name="logout"),
	url(r"^success$", views.success, name="success")
]

django/integration_project/apps/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r"^$", views.index, name="index"),
]

django/integration_project/integration_project/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^', include('apps.urls', namespace='top')),
    url(r'^courses/', include('apps.courses.urls', namespace='courses')),
    url(r'^disappear/', include('apps.disappear.urls', namespace='disappear')),
    url(r'^loginReg/', include('apps.loginReg.urls', namespace='loginReg')),
    url(r'^randomWord/', include('apps.randomWord.urls', namespace='randomWord')),
    url(r'^surveyApp/', include('apps.surveyApp.urls', namespace='surveyApp')),
]

django/integration_project/apps/loginReg/models.py
# from __future__ import unicode_literals

from django.db import models
# from ..courses.models import Course
import bcrypt
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
NAME_REGEX = re.compile(r'^[a-zA-Z][a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
	def register(self, postData):  # for registering a new user
		errors = []
		# Validate all form data
		# first_name, last_name lengths
		if len(postData['first_name']) < 2:
			errors.append('First name: must be at least 2 characters')
		if len(postData['last_name']) < 2:
			errors.append('Last name: must be at least 2 characters')
		# first_name, last_name letters only
		if not NAME_REGEX.match(postData['first_name']):
			errors.append('First name: use letters only')
		if not NAME_REGEX.match(postData['last_name']):
			errors.append('Last name: use letters only')
		# Email - Valid Email format, and that it was submitted
		if not EMAIL_REGEX.match(postData['email']):
			errors.append('Not a valid email address, please re-enter')
		check_user = self.filter(email=postData['email'])
		if check_user:
			errors.append('Email already registered, please login')
		# Password - at least 8 characters, and that it was submitted
		if len(postData['password']) < 8:
			errors.append('Password: must be at least 8 characters')
		# Passwords match
		if not postData['password'] == postData['password_confirmation']:
			errors.append('Passwords do not match, please re-enter')

		if errors:  # If we fail the validations
			# for error in errors:
				# print "ERROR ", type(error), error
			return {'status':False, 'errors':errors}
		else:  # Successfully Registered
			# encrypt password
			password = str(postData['password'])
			hashed_pw = bcrypt.hashpw(password, bcrypt.gensalt())
			# print "PASSWORD= ", hashed_pw
			# create our user
			this_user = self.create(first_name=postData['first_name'], last_name=postData['last_name'], email=postData['email'], password=hashed_pw)
			print "NEW USER= ", this_user.id
			return {'status':True, 'user':this_user}

	def login(self, postData):  # for validating a user login
		errors = []
		# check for user in database
		try:
			this_user = self.get(email=postData['email'])
		except:
			errors.append('Email not registered, try again')
		else:
			# compare password with stored encrypted password
			password = str(postData['password'])
			hashed_pw = str(this_user.password)
			if bcrypt.hashpw(password, hashed_pw) != hashed_pw:
				errors.append('Password invalid, try again')

		if errors:  # If we fail the validations
			# for error in errors:
				# print "ERROR ", type(error), error
			return {'status':False, 'errors':errors}
		else:  # Successfully Logged In
			print "LOGGED IN= ", this_user.id
			return {'status':True, 'user':this_user}

class User(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	email = models.CharField(max_length=100)
	password = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

django/integration_project/apps/loginReg/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User

# Create your views here.
def index(request):
	return render(request, "loginReg/index.html")

def register(request):    # process user registration form
	if request.method == "POST":
		response = User.objects.register(request.POST)
		if response['status'] == False:
			for error in response['errors']:
				messages.error(request, error)
			return redirect("loginReg:index")
		else:
			# password is validated, save user_id for session
			this_user = response['user']
			print "THIS USER ", this_user.id
			request.session['user_id'] = this_user.id
			request.session['first_name'] = this_user.first_name
			return redirect("loginReg:success")
	else:
		return redirect("loginReg:index")

def login(request):    # process user login form
	if request.method == "POST":
		response = User.objects.login(request.POST)
		if response['status'] == False:
			for error in response['errors']:
				messages.error(request, error)
			return redirect("loginReg:index")
		else:
			# password is validated, save user_id for session
			this_user = response['user']
			print "THIS USER ", this_user.id
			request.session['user_id'] = this_user.id
			request.session['first_name'] = this_user.first_name
			return redirect("loginReg:success")
	else:
		return redirect("loginReg:index")

def success(request):
	print request.session
	if not 'user_id' in request.session:
		messages.error(request, "Not logged in, please login or register")
		return redirect("loginReg:index")
	else:
		return render(request, "loginReg/success.html")

def logout(request):    # process user logout form
	if request.method == "POST":
		request.session.clear()
	return redirect("loginReg:index")

django/integration_project/apps/loginReg/templates/loginReg/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login and Registration</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'loginReg/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <div class="main_content">
      <fieldset>
        <legend>Registration</legend>
        <form class="register" action="{% url 'loginReg:register' %}" method="post">
          {% csrf_token %}
          <label for="first_name">
            First Name
            <input type="text" name="first_name">
          </label>
          <label for="last_name">
            Last Name
            <input type="text" name="last_name">
          </label>
          <label for="email">
            Email
            <input type="text" name="email">
          </label>
          <label for="password">
            Password
            <input type="password" name="password" value='password'>
          </label>
          <label for="password_confirmation">
            Confirm Password
            <input type="text" name="password_confirmation" value='password'>
          </label>
          <button type="submit" name="button">Register</button>
        </form>
      </fieldset>
      <fieldset>
        <legend>Login</legend>
        <form class="login" action="{% url 'loginReg:login' %}" method="post">
          {% csrf_token %}
          <label for="email">
            Email
            <input type="email" name="email">
          </label>
          <label for="password">
            Password
            <input type="password" name="password">
          </label>
          <button type="submit" name="button">Login</button>
        </form>
      </fieldset>
      <!-- flash any error messages -->
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
  </body>
</html>

django/integration_project/apps/loginReg/templates/loginReg/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Success Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'loginReg/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <h3>Success! Welcome, {{request.session.first_name}}!</h3>
    <p class="green">Successfully registered (or logged in)!</p>
    <form class="logout" action="{% url 'loginReg:logout' %}" method="post">
      {% csrf_token %}
      <button type="submit" name="button">Logout</button>
    </form>
  </body>
</html>