django/ExamTemplate/BeltExam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.LoginReg.urls', namespace="LoginReg")),
    url(r'^app1/', include('apps.app1.urls', namespace="app1")),
]

django/ExamTemplate/apps/LoginReg/urls.py
from django.conf.urls import url
# Controller - route methods
from . import views
urlpatterns = [
	url(r"^$", views.index, name="index"),
	url(r"^register$", views.register, name="register"),
	url(r"^login$", views.login, name="login"),
	url(r"^logout$", views.logout, name="logout"),
]

django/ExamTemplate/apps/app1/urls.py
from django.conf.urls import url
# Controller - route methods
from . import views
urlpatterns = [
	url(r"^dashboard$", views.dashboard, name="dashboard"),
    url(r"^create_appt$", views.create_appt, name="create_appt"),
	url(r"^edit_appt/(?P<appt_id>\d+)$", views.edit_appt, name="edit_appt"),
	url(r"^update_appt/(?P<appt_id>\d+)$", views.update_appt, name="update_appt"),
    url(r"^delete_appt/(?P<appt_id>\d+)$", views.delete_appt, name="delete_appt"),
]

django/ExamTemplate/apps/app1/models.py
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
import datetime
from datetime import datetime
from datetime import date
from datetime import time
from django.utils import timezone
from django.db import models
from ..LoginReg.models import User

# Create your models Managers here.
class ApptManager(models.Manager):
	def create_appt(self, postData):  # for creating a new appt
		# validate appointment inputs
		errors=[]
		appt_date = postData['appt_date']
		appt_time = postData['appt_time']
		appt_task = postData['appt_task']
		appt_status = postData['appt_status']
		user = postData['user']
		this_date = str(datetime.now().date())
		print "Dates: appt, now", appt_date, this_date
		# validate the date & time represent a current or future date
		if (appt_date < this_date) or (str(appt_date) == ""):
			errors.append('Must enter a current or future date')
		if str(appt_time) == "":
			errors.append('Must enter a time')
		if appt_task == "":
			errors.append('Must enter a task')
		if not errors:	# check for duplicate appointments
			check_appts = self.filter(date=appt_date, time=appt_time)
			if len(check_appts):
				errors.append('This appointment time is already reserved, enter a different time')
		if errors:
			return {'status':False, 'errors':errors}
		else:
			appt = self.create(task=appt_task, date=appt_date, time=appt_time, status=appt_status, user=user)
			return {'status':True, 'appt':appt}

	def update_appt(self, postData):  # for updating an appt
		# validate appointment inputs
		errors=[]
		appt_date = postData['appt_date']
		appt_time = postData['appt_time']
		appt_task = postData['appt_task']
		appt_status = postData['appt_status']
		appt_id = postData['appt_id']
		user = postData['user']
		this_date = str(datetime.now().date())
		print "Dates: appt, now", appt_date, this_date
		# validate the date & time represent a current or future date
		if (appt_date < this_date) or (str(appt_date) == "") :
			errors.append('Must enter a current or future date')
		if str(appt_time) == "":
			errors.append('Must enter a time')
		if appt_task == "":
			errors.append('Must enter a task')
		if not errors:	# check for duplicate appointments
			check_appts = self.filter(date=appt_date, time=appt_time, user=user)
			if len(check_appts):
				errors.append('This appointment time is already reserved, enter a different time')
		if errors:
			return {'status':False, 'errors':errors}
		else:
			appt = self.get(id=appt_id)
			appt.date = appt_date
			appt.time = appt_time
			appt.task = appt_task
			appt.status = appt_status
			appt.save()
			return {'status':True, 'appt':appt}

	def delete_appt(self, postData):  # for deleting an appt
		# validate appointment inputs
		errors=[]
		appt_id = postData['appt_id']
		user = postData['user']
		try:	# check if appt exists
			appt = self.get(id=postData['appt_id'])
		except ObjectDoesNotExist:
			return {'status':False}
		# if appt.user != user:	# ensure this user created the appt
			# return {'status':False}
		appt.delete()	# now delete the appt
		return {'status':True}


# Create your models here.
class Appt(models.Model):
	user = models.ForeignKey(User, related_name="appt_user")
	task = models.CharField(max_length=255)
	date = models.DateField()
	time = models.TimeField()
	status = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = ApptManager()

django/ExamTemplate/apps/app1/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
import datetime
from datetime import datetime
from datetime import date
from datetime import time
from django.utils import timezone
from .models import Appt
from ..LoginReg.models import User

# Create your views here.
def dashboard(request):
	print "DASHBOARD"
	# print request.session
	if not 'user_id' in request.session:
		messages.error(request, "Not logged in, please login or register")
		return redirect("LoginReg:index")

	user = User.objects.get(id=request.session['user_id'])
	this_date = datetime.now().date()
	this_time = datetime.now().time()
	today_appts = Appt.objects.filter(user=user, date=this_date).order_by('-time')
	future_appts = Appt.objects.filter(user=user, date__gt=this_date).order_by('time').order_by('date')
	context = {
		'this_date': this_date,
		'this_time': this_time,
		'today_appts': today_appts,
		'future_appts': future_appts
	}
	return render(request, "app1/dashboard.html", context)

def create_appt(request):
	print "CREATE_APPT"
	if request.method != "POST":
		return redirect("app1:dashboard")
	context = {
		'appt_date': request.POST['appt_date'],
		'appt_time': request.POST['appt_time'],
		'appt_task': request.POST['appt_task'],
		'appt_status': "Pending",
		'user': User.objects.get(id=request.session['user_id'])
	}
	response = Appt.objects.create_appt(context)
	if response['status'] == True:
		print "Done"
	else:
		for error in response['errors']:
			messages.error(request, error)
		print "Failed"
	return redirect("app1:dashboard")

def edit_appt(request, appt_id):
	print "EDIT_APPT"
	context = {
		'this_date': datetime.now().date(),
		'this_time': datetime.now().time(),
		'appt': Appt.objects.get(id=appt_id)
	}
	return render(request, "app1/edit.html", context)

def update_appt(request, appt_id):
	print "UPDATE_APPT"
	if request.method != "POST":
		return redirect("app1:dashboard")
	context = {
		'appt_date': request.POST['appt_date'],
		'appt_time': request.POST['appt_time'],
		'appt_task': request.POST['appt_task'],
		'appt_status': request.POST['appt_status'],
		'appt_id': appt_id,
		'user': User.objects.get(id=request.session['user_id'])
	}
	response = Appt.objects.update_appt(context)
	if response['status'] == True:
		print "Done"
	else:
		for error in response['errors']:
			messages.error(request, error)
		print "Failed"
	return redirect("app1:dashboard")

def delete_appt(request, appt_id):
	print "DELETE_APPT"
	context = {
		'appt_id': appt_id,
		'user': User.objects.get(id=request.session['user_id'])
	}
	response = Appt.objects.delete_appt(context)
	if response['status'] == True:
		print "Done"
	else:
		for error in response['errors']:
			messages.error(request, error)
		print "Failed"
	return redirect("app1:dashboard")

django/ExamTemplate/apps/app1/templates/app1/dashboard.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>What's Up</title>
		{% load tz %}
		{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'app1/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
	</head>
	<body>
		<div class="main_content">
			<h1>Hello, {{ request.session.name }}!</h1>
			<!-- Buttons -->
			<form class="logout" action="{% url 'LoginReg:logout' %}" method="post">
				{% csrf_token %}
				<button type="submit" name="button">Logout</button>
			</form>

			<!-- Display Today's Appointments -->
			<h2>Here are your appointments for today, {{this_date}}</h2>
			<table>
				<thead>
					<tr>
						<th>Tasks</th>
						<th>Time</th>
						<th>Status</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					{% if today_appts %}
						{% for appt in today_appts %}
						<tr>
							<td>{{appt.task}}</td>
							<td>{{appt.time}}</td>
							<td>{{appt.status}}</td>
							{% if appt.status != "Done" %}
								<td><a href="edit_appt/{{appt.id}}">Edit</a> <a href="delete_appt/{{appt.id}}">Delete</a></td>
							{% endif %}
						</tr>
						{% endfor %}
					{% endif %}
				</tbody>
			</table>

			<!-- Display Future Appointments -->
			<h2>Your Future appointments</h2>
			<table>
				<thead>
					<tr>
						<th>Tasks</th>
						<th>Date</th>
						<th>Time</th>
					</tr>
				</thead>
				<tbody>
					{% if future_appts %}
						{% for appt in future_appts %}
						<tr>
							<td>{{appt.task}}</td>
							<td>{{appt.date}}</td>
							<td>{{appt.time}}</td>
						</tr>
						{% endfor %}
					{% endif %}
				</tbody>
			</table>

			<!-- Add Appointment Form -->
			<p></p>
			<hr>
			<p></p>
			<fieldset>
				<legend>Add Appointment</legend>
				<form class="newform" action="{% url 'app1:create_appt' %}" method="post">
					{% csrf_token %}
					<label for="appt_date">Date:
						<input type="date" name="appt_date" value="{{this_date}}">
					</label>
					<label for="appt_time">Time:
						<input type="time" name="appt_time" value="{{this_time}}">
					</label>
					<label for="appt_task">Tasks:
						<input type="text" name="appt_task" value="">
					</label>
					<button type="submit" name="button">Add</button>
				</form>
			</fieldset>

			<!-- flash any error messages -->
			{% if messages %}
				<ul class="messages">
					{% for message in messages %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					{% endfor %}
				</ul>
			{% endif %}
		</div><!-- end_of_main_content-->
	</body>
</html>

django/ExamTemplate/apps/app1/templates/app1/edit.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Update Appointment</title>
		{% load tz %}
		{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'app1/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
	</head>
	<body>
		<div class="main_content">
			<!-- Buttons -->
			<form class="home" action="{% url 'app1:dashboard' %}" method="post">
				{% csrf_token %}
				<button type="submit" name="button">Return to Dashboard</button>
			</form>
			<form class="logout" action="{% url 'LoginReg:logout' %}" method="post">
				{% csrf_token %}
				<button type="submit" name="button">Logout</button>
			</form>

			<!-- Edit Appointment Form -->
			<fieldset>
				<legend>Update Appointment</legend>
				<form class="newform" action="{% url 'app1:update_appt' appt_id=appt.id %}" method="post">
					{% csrf_token %}
					<label for="appt_task">Tasks:
						<input type="text" name="appt_task" value="{{appt.task}}">
					</label>
					<label for="appt_status">Status:
						<select class="dropdown" name="appt_status">
							<option value="{{appt.status}}" selected>{{appt.status}}</option>
							<option value="Pending">Pending</option>
							<option value="Done">Done</option>
							<option value="Missed">Missed</option>
						</select>
					</label>
					<label for="appt_date">Date: set for {{appt.date}}
						<input type="date" name="appt_date" value="{{appt.date}}">
					</label>
					<label for="appt_time">Time: set for {{appt.time}}
						<input type="time" name="appt_time" value="{{appt.time}}">
					</label>
					<button type="submit" name="button">Update</button>
				</form>
			</fieldset>

			<!-- flash any error messages -->
			{% if messages %}
				<ul class="messages">
					{% for message in messages %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					{% endfor %}
				</ul>
			{% endif %}
		</div><!-- end_of_main_content-->
	</body>
</html>