django/integration_project/apps/surveyApp/urls.py
from django.conf.urls import url
# Controller - route methods
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^result$', views.result, name='result'),
    url(r'^process$', views.process, name='process')
]

django/integration_project/apps/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r"^$", views.index, name="index"),
]

django/integration_project/integration_project/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^', include('apps.urls', namespace='top')),
    url(r'^courses/', include('apps.courses.urls', namespace='courses')),
    url(r'^disappear/', include('apps.disappear.urls', namespace='disappear')),
    url(r'^loginReg/', include('apps.loginReg.urls', namespace='loginReg')),
    url(r'^randomWord/', include('apps.randomWord.urls', namespace='randomWord')),
    url(r'^surveyApp/', include('apps.surveyApp.urls', namespace='surveyApp')),
]

django/integration_project/apps/surveyApp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

django/integration_project/apps/surveyApp/views.py
from django.shortcuts import render, HttpResponse, redirect

# Create your views here.
def check_init(request):
    if 'times' in request.session:
        print 'True'
    else:
        request.session['times'] = 0
        print 'False'

def index(request):
    check_init(request)
    return render(request, "surveyApp/index.html")

def result(request):
    return render(request, "surveyApp/result.html")

def process(request):
    if request.method == "POST":
        request.session['times'] = request.session['times'] + 1
        request.session['name'] = request.POST['name']
        request.session['dojo_location'] = request.POST['dojo_location']
        request.session['favorite_language'] = request.POST['favorite_language']
        request.session['comment'] = request.POST['comment']
        print "SESSION= ", request.session
        return redirect("surveyApp:result")
        # context = {
        #     'name': request.POST['name'],
        #     'dojo_location': request.POST['dojo_location'],
        #     'favorite_language': request.POST['favorite_language'],
        #     'comment': request.POST['comment']
        # }
        # print "CONTEXT= ", context
        # return redirect("/result", context)
    else:
        return redirect("surveyApp:index")

django/integration_project/apps/surveyApp/templates/surveyApp/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Survey Form</title>
    {% load staticfiles %}
    <!-- The line above tells Django to be ready to listen for static files -->
    <link rel="stylesheet" href="{% static 'surveyApp/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <h3>Survey Form</h3>
    <div class="line">
      <form action="{% url 'surveyApp:process' %}" method="post">
        {% csrf_token %}
        Your Name: <input type="text" name="name">
        <p></p>
        Dojo Location: <select class="" name="dojo_location">
          <option value="San Jose">San Jose</option>
          <option value="Seattle">Seattle</option>
          <option value="Los Angeles">Los Angeles</option>
          <option value="Dallas">Dallas</option>
          <option value="Washington DC">Washington DC</option>
          <option value="Chicago">Chicago</option>
        </select>
        <p></p>
        Favorite Language: <select name='favorite_language'>
          <option value="Python">Python</option>
          <option value="Java">Java</option>
          <option value="PHP">PHP</option>
          <option value="C#">C#</option>
          <option value="Fortran">Fortran</option>
        </select>
        <p></p>
        <p>Comment (optional):</p>
        <textarea name='comment' rows="5" cols="50"></textarea>
        <input type='submit' value='Submit'>
      </form>
    </div>
  </body>
</html>

django/integration_project/apps/surveyApp/templates/surveyApp/result.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Survey Form: Results</title>
    {% load staticfiles %}
    <!-- The line above tells Django to be ready to listen for static files -->
    <link rel="stylesheet" href="{% static 'surveyApp/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <h3>Thanks for submitting this form! You have submitted this form {{request.session.times}} times now.</h3>
    <div class="line">
      <h4>Submitted Information</h4>
      <p>Name: {{request.session.name}}</p>
      <p>Dojo Location: {{request.session.dojo_location}}</p>
      <p>Favorite Language: {{request.session.favorite_language}}</p>
      <p>Comment: {{request.session.comment}}</p>
      <form action="{% url 'surveyApp:index' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Go Back">
      </form>
    </div>
  </body>
</html>